distributed_ecommerce/forms/AddProductForm.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import InputRequired, Length
from wtforms import StringField, IntegerField, DecimalField, TextAreaField, SelectField, SubmitField

class AddProductForm(FlaskForm):
    product_name = StringField(u'Product name', [InputRequired()])
    category = SelectField(u'Category', choices=[('Others', 'Others'), ('Clothing', 'Clothing'), ('TVs', 'TVs'), ('Home Applicanes', 'Home Applicanes'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics')])
    quantity = IntegerField(u'Quantity', [InputRequired()])
    price = IntegerField(u'Price', [InputRequired()])
    description = TextAreaField(u'Description', [InputRequired()])
    image = FileField(u'Product image', validators=[FileRequired(), FileAllowed(['jpg', 'jpeg', 'png'], 'Images only!')])
    submit = SubmitField('Add product')
    

distributed_ecommerce/forms/CheckoutForm.py
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired, Length
from wtforms import StringField, SubmitField

class CheckoutForm(FlaskForm):
    address = StringField(u'Address', [InputRequired(), Length(min=3, max=3000)])
    phone_number = StringField(u'Phone Number', [InputRequired(), Length(min=7, max=25)])
    submit = SubmitField('Complete Order')

distributed_ecommerce/forms/LogInForm.py
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired, Length
from wtforms import StringField, PasswordField, SubmitField

class LogInForm(FlaskForm):
    username = StringField(u'Username', [InputRequired(), Length(min=3, max=255, message='Must be at least 3 characters long')])
    password = PasswordField(u'Password', [InputRequired(), Length(min=8, max=255, message='Must be at least 3 characters long')])
    submit = SubmitField('Login')   
    

distributed_ecommerce/forms/SignUpForm.py
from flask_wtf import FlaskForm
from wtforms.validators import EqualTo, InputRequired, Length, Email, ValidationError
from wtforms import StringField, PasswordField, TextAreaField, SubmitField

from distributed_ecommerce.models import User2, Shop1

def validate_username(form, username):
    existing_user = User2.query.filter_by(username=username.data).first()
    if existing_user:
        raise ValidationError('This username already exists')

def validate_shop_name(form, shop_name):
    existing_shop = Shop1.query.filter_by(shop_name=shop_name.data).first()
    if existing_shop:
        raise ValidationError('This shop already exists')

def validate_email(form, email):
    existing_user = User2.query.filter_by(email=email.data).first()
    if existing_user:
        raise ValidationError('This email already exists')

class SignUpForm(FlaskForm):
    first_name = StringField(u'First Name', [InputRequired(), Length(min=3, max=255, message='Must be at least 3 characters long')])
    last_name = StringField(u'Last Name', [InputRequired(), Length(min=3, max=255, message='Must be at least 3 characters long')])
    email = StringField(u'Email', [InputRequired(), Email('Please enter a proper email'), Length(max=255), validate_email])
    username = StringField(u'Username', [InputRequired(), Length(min=3, max=255, message='Must be at least 3 characters long'), validate_username])
    shop_name = StringField(u'shop name', [InputRequired(), Length(min=3, max=255, message='Must be at least 3 characters long'), validate_shop_name])
    phone_code = StringField(u'Phone code', [InputRequired(), Length(min=2, max=5, message='Must be at least 2 characters long')])
    phone_number = StringField(u'Phone number', [InputRequired(), Length(min=7, max=25, message='Must be at least 7 characters long and at most 25')])
    address = TextAreaField(u'Address', [InputRequired(), Length(min=3, max=3000, message='Must be at least 3 characters long')])
    password = PasswordField(u'Password', [InputRequired(), Length(min=8, max=255, message='Must be at least 8 characters long')])
    confirm_password = PasswordField(u'Confirm password', [InputRequired(), EqualTo(fieldname='password', message='Must match entered password')])
    submit = SubmitField('Sign Up')  

distributed_ecommerce/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for
import flask
import uuid
import distributed_ecommerce.forms as forms
from db import db
from app_bcrypt import bcrypt
from distributed_ecommerce.models import User1, User2, Shop1, Shop2, Cart1, Cart2
from flask_login import login_required, login_user, logout_user, current_user

auth = Blueprint('auth', __name__, template_folder='templates')

@auth.get('/login')
def login():
    form = forms.LogInForm()
    response = flask.Response(render_template('login.html', form=form))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

@auth.post('/login')
def postlogin():
    form = forms.LogInForm()

    if form.validate_on_submit():
        user = User2.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                response = redirect(url_for('home'))
                response.is_redirectrd = True
                response.headers['Content-Type'] = 'text/html'
                response.headers['status_code'] = 302
                return response

            response = flask.Response(render_template('login.html', form=form, message="Incorrect password"))
            response.headers['Content-Type'] = 'text/html'
            response.headers['status_code'] = 200
            return response
        
        response = flask.Response(render_template('login.html', form=form, message="Incorrect username"))
        response.headers['Content-Type'] = 'text/html'
        response.headers['status_code'] = 200
        return response

    response = flask.Response(render_template('login.html', form=form))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

@auth.get('/logout')
@login_required
def logout():
    logout_user()
    response = redirect(url_for('home'))
    response.is_redirectrd = True
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 302
    return response
    

@auth.get('/signup')
def signup():
    form = forms.SignUpForm()
    if current_user.is_authenticated:
        response = redirect(url_for('home'))
        response.is_redirectrd = True
        response.headers['Content-Type'] = 'text/html'
        response.headers['status_code'] = 302
        return response
    response = flask.Response(render_template('signup.html', form=form))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

@auth.post('/signup')
def postsignup():
    form = forms.SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        created_user1 = User1(user_id=str(uuid.uuid4()), first_name=form.first_name.data, last_name=form.last_name.data, address=form.address.data, phone_code=form.phone_code.data, phone_number=form.phone_number.data)
        created_user2 = User2(username=form.username.data, email=form.email.data, password=hashed_password, user_id=created_user1.user_id)
        created_shop1 = Shop1(shop_id=str(uuid.uuid4()), shop_name=form.shop_name.data)
        created_shop2 = Shop2(user_id=created_user1.user_id, shop_id=created_shop1.shop_id)
        created_cart1 = Cart1(cart_id=str(uuid.uuid4()))
        created_cart2 = Cart2(cart_id=created_cart1.cart_id, user_id=created_user1.user_id)
        
        db.session.add(created_user1)
        db.session.add(created_shop1)
        db.session.add(created_cart1)

        db.session.add(created_user2)
        db.session.add(created_shop2)
        db.session.add(created_cart2)
        
        db.session.commit()
        
        login_user(created_user2)
        response = redirect(url_for('home'))
        response.is_redirectrd = True
        response.headers['Content-Type'] = 'text/html'
        response.headers['status_code'] = 302
        return response
    if current_user.is_authenticated:
        response = redirect(url_for('home'))
        response.is_redirectrd = True
        response.headers['Content-Type'] = 'text/html'
        response.headers['status_code'] = 302
        return response
    response = flask.Response(render_template('signup.html', form=form))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

distributed_ecommerce/blueprints/shop.py
from flask import Blueprint, render_template, redirect, url_for, request
import flask
import uuid
from distributed_ecommerce.blueprints.auth import login
from distributed_ecommerce.forms.AddProductForm import AddProductForm
from db import db
from distributed_ecommerce.models import User1, User2, Product1, Product2, Shop1, Shop2, Transaction1, Transaction2
from flask_login import login_required, current_user
import os
from werkzeug.utils import secure_filename


shop = Blueprint('shop', __name__, template_folder='templates')

@shop.get('/shop')
@login_required
def dashboard():
    shop = current_user.shop
    products = shop.products
    
    for p in products:
        product = Product1.query.filter_by(product_id=p.product_id).first()
        p.product_name = product.product_name
        p.category = product.category
        p.price = product.price
        p.quantity = product.quantity
        p.quantity_in_cart = product.quantity_in_cart
        p.description = product.description
        p.image = product.image
    
    response = flask.Response(render_template('shopdashboard.html',shop=shop, products=products))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

@shop.get('/shop/<shop_id>')
def shop_view(shop_id):
    shop = Shop2.query.get(shop_id)
    if shop:
        shop1 = Shop1.query.get(shop_id)
        shop.shop_name = shop1.shop_name
        user = User2.query.get(shop.user_id)
        products = shop.products
        for product in products:
            p = Product1.query.get(product.product_id)
            product.product_name = p.product_name
            product.price = p.price
            product.image = p.image
            product.description = p.description
            product.category = p.category
            product.quantity = p.quantity

        response = flask.Response(render_template('shop.html', shop=shop, shop_owner=user, products=products))
        response.headers['Content-Type'] = 'text/html'
        response.headers['status_code'] = 200
        return response
    
    response = flask.Response('Error 404.<br> Shop not found')
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 404
    return response

@shop.get('/shop/addproduct')
@login_required
def addproduct():
    form = AddProductForm()
    response = flask.Response(render_template('addproduct.html', form=form))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

@shop.post('/shop/addproduct')
@login_required
def postaddproduct():
    form = AddProductForm()
    if form.validate_on_submit():
        # get the user's shop.
        shop = Shop2.query.filter_by(user_id=current_user.user_id).first()

        # get the image
        image = form.image.data
        image_name = secure_filename(image.filename)

        # craete product
        created_product1 = Product1(product_id=str(uuid.uuid4()),product_name=form.product_name.data, category=form.category.data, quantity=form.quantity.data, price=form.price.data, description=form.description.data, image=image_name)
        created_product2 = Product2(product_id=created_product1.product_id, user_id=current_user.user_id)
        shop.products.append(created_product2)
        db.session.add(created_product1)
        db.session.add(created_product2)
        db.session.commit()

        # save the image
        image.save(os.path.join(os.getcwd(), 'images', image_name))

        response = redirect(url_for('productpage', product_id=created_product1.product_id))
        response.is_redirectrd = True
        response.headers['Content-Type'] = 'text/html'
        response.headers['status_code'] = 302
        return response

    response = flask.Response(render_template('addproduct.html', form=form))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

@shop.get('/shop/orders')
@login_required
def orders():
    response = flask.Response(render_template('shoporders.html'))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response


@shop.get('/shop/report')
@login_required
def getshopreport():
    transaction1 = Transaction1.query.all()
    transaction2 = Transaction2.query.all()
    transactions = []
    for t1 in transaction1:
        for t2 in transaction2:
            if t1.transaction_id != t2.transaction_id:
                continue
            elif t1.transaction_id == t2.transaction_id and (t2.new_shop == current_user.shop.shop_id or t2.owner_shop == current_user.shop.shop_id):
                product = Product1.query.filter_by(product_id=t2.product_id).first()
                product2 = Product2.query.filter_by(product_id=t2.product_id).first()
                owner = Shop2.query.filter_by(user_id=product2.user_id).first()
                owner_shop = Shop1.query.filter_by(shop_id=owner.shop_id).first()

                add_to_shop = True if (t1.transaction_type == "Add to shop") else False
                new_shop = None
                buyer = None
                quantity = None
                cost = None
                if add_to_shop:
                    new_shop = Shop1.query.filter_by(shop_id=t2.new_shop).first()
                else:
                    buyer = User2.query.filter_by(user_id=t2.buyer).first()
                    quantity = t2.quantity
                    cost = quantity * product.price
                t = {
                    "type": t1.transaction_type,
                    "product":product.product_name,
                    "owner": owner_shop.shop_name,
                    "new_shop": None if not new_shop else new_shop.shop_name,
                    "buyer": None if not buyer else buyer.username,
                    "quantity": None if not quantity else quantity,
                    "cost": None if not cost else cost
                }
                transactions.append(t)
                break
    response = flask.Response(render_template('report.html', report=transactions))
    response.headers['Content-Type'] = 'text/html'
    response.headers['status_code'] = 200
    return response

distributed_ecommerce/templates/AddCoupon.html
{% extends 'templates/layoutshop.html' %} {% block head %}
<title>Add coupon</title>

<style>
  .add_coupon {
    margin-left: 35%;
  }
  input[type='text'] {
    display: block;
    width: 300px;
    margin-top: 20px;
    margin-bottom: 5px;
  }
  input::-webkit-outer-spin-button,
  input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }

  /* Firefox */
  input[type='number'] {
    -moz-appearance: textfield;
  }
  input[type='submit'] {
    display: block;
    margin: 20px;
    margin-left: 12%;
    width: 140px;
    height: 30px;
    border-radius: 10px;
    background: #2c578f;
    color: white;
    font-weight: bold;
  }
  input[type='submit']:hover,
  .deactivate:hover {
    cursor: pointer;
    color: #fff;
  }
  #submit_btn[disabled],
  #submit_btn:disabled {
    cursor: default;
    color: #ccc;
  }
  .coupons {
    margin: 10px;
    border: #bfb367 4px solid;
  }
  .deactivate {
    width: 120px;
    height: 30px;
    background-color: #232732;
    font-weight: bold;
  }
  .deactivate a {
    color: #bfb367;
    text-decoration: none;
  }
  .deactivate a:hover {
    color: #fff;
  }
  #discount {
    width: 300px;
  }
</style>
{% endblock %} {% block body %}
<div class="add_coupon">
  <form action="{% url 'addcoupon' %}" method="POST">
    {% csrf_token %}
    <input type="text" id="name" placeholder="Coupon name" name="name" />
    <input
      type="number"
      id="discount"
      placeholder="Discount percentage"
      name="discount"
    />
    <input type="submit" id="submit_btn" value="Generate coupon" disabled />
  </form>
</div>
{% if success %}
<div style="text-align: center; margin-bottom: 8px">
  <strong style="color: green; margin: 6%">{{ message }}</strong>
</div>
{% else %}
<div style="text-align: center; margin-bottom: 8px">
  <strong style="color: red; margin: 6%">{{ message }}</strong>
</div>
{% endif %}
<script>
  var namee = document.getElementById('name');
  var discount = document.getElementById('discount');
  var submit = document.getElementById('submit_btn');
  function check() {
    if (
      namee.value.length > 2 &&
      discount.value.length > 0 &&
      discount.value.length < 3
    ) {
      submit.disabled = false;
    } else submit.disabled = true;
  }
  namee.addEventListener('input', check);
  discount.addEventListener('input', check);
</script>
{% endblock %}

distributed_ecommerce/templates/Mainpage.html
{% extends 'layoutuser.html' %}
{% block head %} 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
    <script src="https://kit.fontawesome.com/8d4c067090.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title> Vividly Official Page </title>
{% endblock %}
{% block body %}
    <section class="collection">
        <div class="container py-5">
          <form method="POST">
            <div class="search">
              <input type="text" name="search_name" id="s" placeholder="What are you looking for ?">
              <button type="submit" id="b" disabled><i class="fa fa-search"></i> Search</button>
            </div>
            </form>    
                  {% for shop in shops %} 
                    <div class="item">
                      {% if shop == current_user.shop and shop.products %}
                        <h3>My Shop: </h3>
                      {% else %}
                      {% if shop.products %}
                        <h3 id="shopname" ><a href="{{ url_for('shop.shop_view',shop_id=shop.shop_id) }}">{{ shop.shop_name }}'s Products: </a></h3>
                      {% endif %}
                      {% endif %}
                      {% if shop.products %}
                        {% for product in shop.products %} 
                        <div class="card mb-3 border-0 ">
                          <img src="{{ url_for('uploaded_file', filename=product.image) }}" class="img-fluid mb-3" />
                          <h5><a href="{{ url_for('productpage',product_id=product.product_id) }}">{{ product.product_name }}</a></h5>
                          <p><small><span>{{ product.price }} L.E</span> </small> </p>
                          {% if current_user.is_authenticated and product.user_id != current_user.user_id %}
                            <div class="buttons d-flex flex-row">
                              <!-- <button class="btn"><i class="fa fa-shopping-cart"></i>   Add to cart</button> -->
                              <form class="add-to-cart-form" action="{{ url_for('order.addtocart') }}" method="PUT">
                                <input type="hidden" name="p_id" class="p_id" value="{{ product.product_id }}">
                                <button type="submit" name="add_to_cart" class="btn add_to_cart_button"
                                {% if product.product_id in current_user_products_in_cart %}
                                  disabled style="background-color: gray;"
                                {% endif %}
                                >
                                  <i class="fa fa-shopping-cart"></i> Add to Cart
                                </button>
                                <div class="alert-message">
                                </div>
                              </form>
                            </div>
                          {% endif %}
                        </div>
                        {% endfor %} 
                        {#
                        {% else %}
                        <small><span>This Shop Currently Has No Products</span> </small>
                        #}
                      {% endif %}
                    </div>
                  {% endfor %} 
                  </div>
                </div>
{#    <!---------------------Footer-----------------> #}
       
<div class="copyright">
  <div class="container wrap">
            <div class="row">
                <div class="footer col-md-3">
                    <div class="about footer-widget">
                        <h2 class="widget-title">About</h2>
                        <p>
                          Vividly is your number one online shopping site in Nigeria. We are an online store where you can purchase all your electronics, as well as books, home appliances, kiddies items, fashion items and more on the go.
                        </p>
                        <div class="cards">
                            <i class="fab fa-cc-mastercard"></i>
                            <i class="fab fa-paypal"></i>
                            <i class="fab fa-cc-amex"></i>
                            <i class="fab fa-cc-discover"></i>
                            <i class="fab fa-cc-apple-pay"></i>
                            <i class="fab fa-cc-visa"></i>
                        </div>
                        <p><span><i class="fas fa-lock"></i></span> Secured Payment </p>
                    </div>


                </div>
                <div class="categories col-md-3">
                    <div class="footer-widget categories-widget">
                        <h2 class="widget-title">Categories</h2>
                        <ul>
                            <li>
                                <a >Clothing</a>

                            </li>
                            <li>
                                <a >Tvs</a>

                            </li>
                            <li>
                                <a >Electronics</a>

                            </li>
                            <li>
                                <a >Home Appliances</a>

                            </li>
                            <li>
                                <a >Furniture</a>

                            </li>
                            <li>
                                <a>Others</a>

                            </li>


                        </ul>


                    </div>

                </div>

                
                  <div class="address col-md-3">
                    <div class="footer-widget">
                        <h2 class="widget-title">Address</h2>
                        <div class="contact-address">
                            <i class="fas fa-map-marker-alt"></i>Address:Nasr City,Cairo.Egypt
                        </div>
                        <div class="contact-email"><i class="fas fa-envelope"></i>Email: mm566464@vividly.com</div>
                    </div>
                   </div>

            </div>
          </div>
</div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='js/home.js') }}"></script>
  <script>
    let catheads = document.getElementsByClassName('cathead');
    let cur = document.getElementById('cur');
    let cats = document.getElementsByClassName('cat');
    let cur_cat = document.getElementById('cur_cat');
    let search = document.getElementById('s');
    let search_btn = document.getElementById('b');


    for(let i=0;i<catheads.length;i++){
        catheads[i].children[0].addEventListener('click',function(){
            cur.id='';
            window.event.target.id='cur';
            cur=window.event.target;
            let current_category=cur.innerHTML;
            for(let i=0;i<6;i++){
                if (cats[i].children[0].innerHTML==current_category)
                    cats[i].style="display:block";
                else
                    cats[i].style="display:none";
            }
        });
    }
  </script>
{% endblock %}

distributed_ecommerce/templates/layoutuser.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %}{% endblock %}
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap"
      rel="stylesheet"
    />
    <link
      href="{{ url_for('static', filename='css/layoutuser.css') }}"
      rel="stylesheet"
    />
  </head>

  <body>
    <div class="wrapper"></div>
    <div class="mobile-nav">
      <nav>
        <ul>
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('home') }}"> Home </a></li>
          <li><a href="{{ url_for('userdashboard') }}"> Profile </a></li>
          <li>
            <a href="{{ url_for('userdashboard') }}"> My Account </a>
          </li>

          {#
          <li><a href="{% url 'shopdashboard' %}"> My shop </a> {% endif %}</li>
          #} {#
          <li><a href="{% url 'orders' %}"> Orders </a></li>
          #} {#
          <li><a href="{% url 'wishlist' %}"> Wishlist </a></li>
          #}
          <li><a href="{{ url_for('order.cart') }}"> Cart </a></li>

          <li><a href="{{ url_for('contactus') }}"> Contact Us </a></li>
          <li><a href="{{ url_for('getreport') }}"> Report </a></li>
          <li><a href="{{ url_for('auth.logout') }}"> Logout </a></li>
          {% else %}
          <li><a href="{{ url_for('home') }}"> Home </a></li>
          <li><a href="{{ url_for('auth.signup') }}">SignUp</a></li>
          <li><a href="{{ url_for('auth.login') }}"> Login </a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <header>
      <div class="logo-burger-search">
        {% if current_user.is_authenticated %}
        <div class="burgers">
          <div class="burger burger-one"></div>
          <div class="burger burger-two"></div>
          <div class="burger burger-three"></div>
        </div>
        {% endif %}
        <div class="logo">
          <div class="BlackJack">
            <a id="BlackJack" href="{{ url_for('home') }}">Vividly</a>
          </div>
          <div class="official">
            <a id="official" href="{{ url_for('home') }}"
              >The Official online store</a
            >
          </div>
        </div>
      </div>

      <nav>
        <ul>
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('home') }}"> Home </a></li>
          <li><a href="{{ url_for('userdashboard') }}"> Profile </a></li>
          <li><a href="{{ url_for('contactus') }}"> Contact Us </a></li>
          <li><a href="{{ url_for('getreport') }}"> Report </a></li>
          <li><a href="{{ url_for('auth.logout') }}"> Logout </a></li>
          {% else %}
          <li><a href="{{ url_for('home') }}"> Home </a></li>
          <li><a href="{{ url_for('auth.signup') }}">SignUp</a></li>
          <li><a href="{{ url_for('auth.login') }}"> Login </a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    {% if current_user.is_authenticated %}
    <section class="sidemenu">
      <span class="dashboard"> DASHBOARD </span>
      <nav>
        <ul>
          <li>
            <a href="{{ url_for('userdashboard') }}"> My Account </a>
          </li>

          <li><a href="{{ url_for('shop.dashboard') }}"> My shop </a></li>
          {#
          <li><a href="{% url 'orders' %}"> Orders </a></li>
          <li><a href="{% url 'wishlist' %}"> Wishlist </a></li>
          #}
          <li><a href="{{ url_for('order.cart') }}"> Cart </a></li>
        </ul>
      </nav>
    </section>
    {% endif %}

    <main role="main">
      {#
      <div id="upperinfo">
        <h1>{% block name %} {% endblock %}</h1>
      </div>
      #}
      <div id="info">{% block body %} {% endblock %}</div>
    </main>
    <script>
      var menu_open = false;
      const sidemenu = document.querySelector('.sidemenu');
      const header = document.querySelector('header');
      const burgers = document.querySelector('.burgers');
      const main = document.querySelector('main');
      const wrapper = document.querySelector('.wrapper');
      const mobile = document.querySelector('.mobile-nav');
      const search_input = document.querySelector('.search-field');
      const search_bar = document.querySelector('.search-bar');
      document.addEventListener('click', function (event) {
        if (
          !sidemenu.contains(event.target) &&
          menu_open &&
          event.target != burgers &&
          !burgers.contains(event.target)
        ) {
          for (let i = 0; i < burgers.children.length; i++) {
            burgers.children[i].classList.remove('clicked');
          }
          sidemenu.classList.remove('shown');
          main.classList.remove('shrink');
          wrapper.classList.remove('grey-out');
          menu_open = false;
        }
      });
      burgers.addEventListener('click', function () {
        if (!menu_open) {
          for (let i = 0; i < burgers.children.length; i++) {
            burgers.children[i].classList.add('clicked');
          }
          sidemenu.classList.add('shown');
          main.classList.add('shrink');
          wrapper.classList.add('grey-out');
          mobile.classList.add('open');
          menu_open = true;
        } else {
          for (let i = 0; i < burgers.children.length; i++) {
            burgers.children[i].classList.remove('clicked');
          }
          main.classList.remove('shrink');
          sidemenu.classList.remove('shown');
          wrapper.classList.remove('grey-out');
          mobile.classList.remove('open');
          menu_open = false;
        }
      });

      function resize() {
        const body = document.querySelector('body');
        if (header.clientHeight + main.clientHeight < body.clientHeight)
          document.querySelector(
            '.wrapper'
          ).style = `height:${body.clientHeight}px`;
        else
          document.querySelector('.wrapper').style = `height:${
            header.clientHeight + main.clientHeight + 6
          }px`;
      }

      const resizeObserver = new ResizeObserver((entries) => {
        resize();
      });

      // start observing a DOM node
      resizeObserver.observe(main);

      document.addEventListener('click', function () {
        if (search_input === document.activeElement) {
          search_bar.classList.add('focused');
        } else {
          search_bar.classList.remove('focused');
        }
      });
    </script>
  </body>
</html>